"""user_role: add the UPPERCASE labels SQLAlchemy actually emits

Revision ID: 20260810_role_case
Revises: 20260804_role_values
Create Date: 2026-08-10

THE BUG THIS FIXES

    POST /users with role=SECURITY died on Postgres with

        asyncpg.exceptions.InvalidTextRepresentationError:
        invalid input value for enum user_role: "SECURITY"

    ...even though 20260804_role_values had already run and 'security' WAS a
    label on the type. Both facts are true at once, and that is the whole trap.

WHY 'security' WAS NOT ENOUGH

    `Enum(UserRole, name="user_role")` stores the enum MEMBER NAME, not its
    value. SQLAlchemy only stores the value if you hand it
    `values_callable=lambda e: [m.value for m in e]`, which this project never
    did. So for UserRole.SECURITY = "security", the driver sends the string
    'SECURITY' — the NAME — and Postgres, holding only the lowercase label
    'security', rejects it.

    The baseline (20260613_1238) got this right by accident: it was autogenerated
    by Alembic, so it created the type from the NAMES:
        'MANAGING_DIRECTOR', 'DIRECT_MANAGER', ... 'HR'   (9 uppercase labels)

    The two follow-up migrations were hand-written from the enum's VALUES:
        20260730_barcode      -> 'lining_manager'
        20260804_role_values  -> 'security', 'merchandiser'

    ...so those three roles were added in a case the ORM will never emit. The
    live type ended up split down the middle: 9 usable uppercase labels and 3
    dead lowercase ones. LINING_MANAGER and MERCHANDISER logins were broken by
    exactly the same mechanism as SECURITY — SECURITY was simply the first one
    anybody tried to create.

THE FIX

    Add the three names. This is additive and matches the convention the other
    three native enums in this schema already follow (attendance_source,
    wage_type, run_status are all uppercase names).

    The alternative — switching the column to `values_callable` so it persists
    values — was rejected: every existing app_user row stores an UPPERCASE name,
    so that flip would orphan all 8 live logins and require a data migration of
    the column plus the type. Adding 3 labels touches no rows.

    The dead lowercase labels are left in place. PostgreSQL cannot drop a value
    from an enum type without recreating the type and rewriting every dependent
    column, and no row carries them (verified before writing this migration), so
    they are inert. Do not add lowercase labels here again.

RULE FOR THE NEXT ROLE (CLAUDE.md §13)

    Adding a member to the Python UserRole enum needs a matching
    ALTER TYPE user_role ADD VALUE '<MEMBER_NAME_UPPERCASE>' — the NAME, spelled
    exactly as it appears on the left of the `=` in core/enums.py, NOT the
    lowercase string on the right.

F63: ALTER TYPE ... ADD VALUE is committed on its own via autocommit_block(),
same reasoning as the two migrations above. Safe to re-run — every statement is
ADD VALUE IF NOT EXISTS.

No-op on SQLite (the test stand-in), where there is no native enum type.
"""
from alembic import op

revision = "20260810_role_case"
down_revision = "20260804_role_values"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'LINING_MANAGER'")
            op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SECURITY'")
            op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'MERCHANDISER'")


def downgrade() -> None:
    # PostgreSQL cannot remove a value from an enum type. Removing it would mean
    # recreating the type and rewriting every dependent column — far more
    # destructive than the extra values are worth. Deliberate no-op.
    pass
