"""bom
Revision ID: abc0437cbe06
Revises: c7a2d5b81f60
Create Date: 2026-06-21 15:41:30.019191
"""
from alembic import op
import sqlalchemy as sa

revision = 'abc0437cbe06'
down_revision = 'c7a2d5b81f60'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
