"""Undo the inferred garment_size on accessory recipe lines.

WHY THIS EXISTS AS ITS OWN REVISION

    It used to be half of `20260927_kit_packet_scan`, which also created
    `kit_substitution_request`. That revision was deleted when the chain was
    squashed into the `1d4a32009101` baseline on 2026-09-28. The TABLE survived the
    squash, because the baseline is autogenerated from the models and the model was
    still there. The DATA FIX did not — a squashed baseline describes a schema, and
    a fresh database has no rows to correct, so autogenerate has nothing to carry
    over. This revision is that fix, carried over by hand.

WHAT WAS WRONG

    `style_material_spec.garment_size` scopes a recipe line to one garment size. It
    used to be GUESSED from the material's own size whenever that size read as a
    garment size — and ANY bare number from 30 to 70 read as one, because those are
    the EU jacket rungs. So a 60 cm zip entered as size '60' was read as a size-60
    garment, mapped to 4XL, and scoped to 4XL jackets only. A 45 cm zip went to XS.

    That is not a smaller recipe for the other sizes. A line that reaches no garment
    is ABSENT: `merge_lines` drops it, `kit_required` comes back False,
    `piece_complete` collapses to leather-and-lining, and every garment of every
    other size is complete, sendable and shipped WITHOUT its zip. Nothing warns,
    because from the garment's point of view the style declares no accessories.

    So the guess is undone here: where an ACCESSORY line's `garment_size` is
    identical to a purely NUMERIC material size, it was the inference and not a
    human, and it goes back to NULL — every size, which is what an unscoped line has
    always meant. The release gate then asks the DM to confirm or split those lines
    (`kit_rules.accessory_size_gaps` / `accessory_size_ambiguities`), which is the
    right place for the question: release is the last moment anyone can be asked.

    ALPHA sizes are left ALONE. 'L' next to garment_size 'L' is a line somebody
    meant, and clearing it would widen a genuinely size-specific button to every
    garment — the opposite error, and that one spends stock rather than skipping it.

SAFE ON A CLEAN DATABASE. It is idempotent and matches nothing on a database built
fresh from the baseline, which is why it is applied unconditionally rather than after
an audit: the alternative was deleting a real fix on the assumption that no database
needs it.

Revision ID: 20260928_garment_size_backfill
Revises: 1d4a32009101
"""
from alembic import op
import sqlalchemy as sa

from app.core.models import GUID

revision = "20260928_garment_size_backfill"
down_revision = "1d4a32009101"
branch_labels = None
depends_on = None


def _spec_table():
    return sa.table(
        "style_material_spec",
        sa.column("id", GUID()),
        sa.column("category", sa.String),
        sa.column("size", sa.String),
        sa.column("garment_size", sa.String),
    )


def clear_inferred_garment_sizes(bind) -> int:
    """Undo the numeric-size inference. Returns how many lines were freed.

    A MODULE-LEVEL FUNCTION, NOT INLINE IN upgrade(), so it can be tested. Since the
    squash the chain's DDL does apply on SQLite, but an alembic-built SQLite database
    still cannot be written to: the baseline sets `server_default=sa.text('now()')` on
    every created_at/updated_at (138 of them) and SQLite has no `now()`, so every
    INSERT fails. So the fix cannot be exercised by running the chain either way, and
    a data fix that can only be run for the first time on production is a data fix
    nobody has tested. This one is exercised by
    tests/integration/test_garment_size_backfill.py against a create_all schema.

    DONE IN PYTHON, NOT SQL, because "is this string all digits" is spelled three
    different ways across Postgres and SQLite (~, REGEXP, GLOB). One SELECT and one
    UPDATE per row is affordable: these are recipe lines, in the dozens.
    """
    spec = _spec_table()
    rows = bind.execute(
        sa.select(spec.c.id, spec.c.size, spec.c.garment_size).where(
            spec.c.category == "ACCESSORY",
            spec.c.garment_size.isnot(None),
            spec.c.size.isnot(None),
        )
    ).fetchall()

    cleared = 0
    for row_id, size, garment_size in rows:
        size_token = str(size or "").strip()
        # ONLY where the two are the same string AND that string is a bare number.
        # Same-but-alpha ('L' / 'L') is a line a human meant, and clearing it would
        # widen a genuinely size-specific button to every garment — the opposite
        # error, and that one spends stock. Different values mean somebody set
        # garment_size explicitly and it is not ours to touch.
        if not size_token.isdigit():
            continue
        if size_token.upper() != str(garment_size or "").strip().upper():
            continue
        bind.execute(
            sa.update(spec).where(spec.c.id == row_id)
            .values(garment_size=None))
        cleared += 1
    return cleared


def upgrade() -> None:
    cleared = clear_inferred_garment_sizes(op.get_bind())
    print(f"[20260928_garment_size_backfill] cleared inferred garment_size on "
          f"{cleared} accessory recipe line(s) — they now apply to every size, "
          f"and the release gate will ask the DM to confirm or split them.")


def downgrade() -> None:
    """A NO-OP, DELIBERATELY, and it is not laziness.

    Re-deriving `garment_size` from a numeric material size would restore the very
    bug this removes. It is also not recoverable: after the upgrade, a line this
    cleared and a line a human deliberately left unscoped are the same row, so there
    is nothing to tell them apart by.
    """
