"""new-changes-1
Revision ID: 2443601a7f8a
Revises: f8b6f6527443
Create Date: 2026-06-10 15:16:20.134501
"""
from alembic import op
import sqlalchemy as sa

revision = '2443601a7f8a'
down_revision = 'f8b6f6527443'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
