"""local-db-updating-db
Revision ID: 8121fef45579
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 13:20:16.312973
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '8121fef45579'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_config')
    op.drop_index(op.f('ix_attendance_log_employee_id'), table_name='attendance_log')
    op.drop_index(op.f('ix_attendance_log_work_date'), table_name='attendance_log')
    op.drop_table('attendance_log')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_log',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('check_out_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.ENUM('SELF', 'PROXY', name='attendance_source'), autoincrement=False, nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_late', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_short', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_overtime', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('distance_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('attendance_log_employee_id_fkey')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], name=op.f('attendance_log_recorded_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_log_pkey')),
    sa.UniqueConstraint('employee_id', 'work_date', name=op.f('uq_att_emp_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attendance_log_work_date'), 'attendance_log', ['work_date'], unique=False)
    op.create_index(op.f('ix_attendance_log_employee_id'), 'attendance_log', ['employee_id'], unique=False)
    op.create_table('shift_config',
    sa.Column('shift_start', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('shift_length_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('late_grace_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('factory_lat', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=False),
    sa.Column('factory_lon', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=False),
    sa.Column('radius_m', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_config_pkey'))
    )
    # ### end Alembic commands ###
