"""new-changes
Revision ID: b78ee9aeb180
Revises: 78b29ac722f7
Create Date: 2026-06-10 13:27:44.247263
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision = 'b78ee9aeb180'
down_revision = '78b29ac722f7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_table('employee',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('wage_type', sa.Enum('MONTHLY', 'PIECE_RATE', 'DAILY_WAGE', name='wage_type'), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_index(op.f('ix_employee_phone'), 'employee', ['phone'], unique=False)
    op.create_table('operation',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('wage_run',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='run_status'), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('DIRECT_MANAGER', 'CUTTING_MANAGER', 'STITCHING_MANAGER', 'EMPLOYEE', 'CLIENT', 'VIEWER', 'SUPERVISOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('employee_id', UUID(as_uuid=True), nullable=True),
    sa.Column('client_id', UUID(as_uuid=True), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_client_id'), 'app_user', ['client_id'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_employee_id'), 'app_user', ['employee_id'], unique=False)
    op.create_index(op.f('ix_app_user_name'), 'app_user', ['name'], unique=False)
    op.create_index(op.f('ix_app_user_phone'), 'app_user', ['phone'], unique=True)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_table('operation_access',
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('operation_id', UUID(as_uuid=True), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'operation_id', name='uq_role_operation')
    )
    op.create_index(op.f('ix_operation_access_role'), 'operation_access', ['role'], unique=False)
    op.create_table('purchase_order',
    sa.Column('client_id', UUID(as_uuid=True), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('delivery_deadline', sa.Date(), nullable=True),
    sa.Column('sea_cutoff_date', sa.Date(), nullable=True),
    sa.Column('ship_mode', sa.String(length=10), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_client_id'), 'purchase_order', ['client_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_po_number'), 'purchase_order', ['po_number'], unique=False)
    op.create_table('wage_line',
    sa.Column('wage_run_id', UUID(as_uuid=True), nullable=False),
    sa.Column('employee_id', UUID(as_uuid=True), nullable=False),
    sa.Column('wage_type', sa.String(length=20), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['wage_run_id'], ['wage_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wage_line_employee_id'), 'wage_line', ['employee_id'], unique=False)
    op.create_index(op.f('ix_wage_line_wage_run_id'), 'wage_line', ['wage_run_id'], unique=False)
    op.create_table('style',
    sa.Column('purchase_order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('article', sa.String(length=80), nullable=True),
    sa.Column('thickness', sa.String(length=40), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_name'), 'style', ['name'], unique=False)
    op.create_index(op.f('ix_style_purchase_order_id'), 'style', ['purchase_order_id'], unique=False)
    op.create_table('rate',
    sa.Column('style_id', UUID(as_uuid=True), nullable=False),
    sa.Column('operation_id', UUID(as_uuid=True), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'operation_id', 'effective_from', name='uq_rate')
    )
    op.create_index(op.f('ix_rate_operation_id'), 'rate', ['operation_id'], unique=False)
    op.create_index(op.f('ix_rate_style_id'), 'rate', ['style_id'], unique=False)
    op.create_table('sku',
    sa.Column('style_id', UUID(as_uuid=True), nullable=False),
    sa.Column('color_code', sa.String(length=40), nullable=False),
    sa.Column('color_name', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'color_code', 'size', name='uq_sku_identity')
    )
    op.create_index(op.f('ix_sku_style_id'), 'sku', ['style_id'], unique=False)
    op.create_table('style_operation',
    sa.Column('style_id', UUID(as_uuid=True), nullable=False),
    sa.Column('operation_id', UUID(as_uuid=True), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'operation_id', name='uq_style_operation')
    )
    op.create_index(op.f('ix_style_operation_style_id'), 'style_operation', ['style_id'], unique=False)
    op.create_table('production_event',
    sa.Column('sku_id', UUID(as_uuid=True), nullable=False),
    sa.Column('operation_id', UUID(as_uuid=True), nullable=False),
    sa.Column('employee_id', UUID(as_uuid=True), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('bundle_ref', sa.String(length=60), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_event_bundle_ref'), 'production_event', ['bundle_ref'], unique=False)
    op.create_index(op.f('ix_production_event_employee_id'), 'production_event', ['employee_id'], unique=False)
    op.create_index(op.f('ix_production_event_operation_id'), 'production_event', ['operation_id'], unique=False)
    op.create_index(op.f('ix_production_event_sku_id'), 'production_event', ['sku_id'], unique=False)
    op.create_index(op.f('ix_production_event_work_date'), 'production_event', ['work_date'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_event_work_date'), table_name='production_event')
    op.drop_index(op.f('ix_production_event_sku_id'), table_name='production_event')
    op.drop_index(op.f('ix_production_event_operation_id'), table_name='production_event')
    op.drop_index(op.f('ix_production_event_employee_id'), table_name='production_event')
    op.drop_index(op.f('ix_production_event_bundle_ref'), table_name='production_event')
    op.drop_table('production_event')
    op.drop_index(op.f('ix_style_operation_style_id'), table_name='style_operation')
    op.drop_table('style_operation')
    op.drop_index(op.f('ix_sku_style_id'), table_name='sku')
    op.drop_table('sku')
    op.drop_index(op.f('ix_rate_style_id'), table_name='rate')
    op.drop_index(op.f('ix_rate_operation_id'), table_name='rate')
    op.drop_table('rate')
    op.drop_index(op.f('ix_style_purchase_order_id'), table_name='style')
    op.drop_index(op.f('ix_style_name'), table_name='style')
    op.drop_table('style')
    op.drop_index(op.f('ix_wage_line_wage_run_id'), table_name='wage_line')
    op.drop_index(op.f('ix_wage_line_employee_id'), table_name='wage_line')
    op.drop_table('wage_line')
    op.drop_index(op.f('ix_purchase_order_po_number'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_client_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_operation_access_role'), table_name='operation_access')
    op.drop_table('operation_access')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_phone'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_name'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_employee_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_client_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('wage_run')
    op.drop_table('operation')
    op.drop_index(op.f('ix_employee_phone'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
