"""add new service tables
Revision ID: b7af20f6f3bb
Revises: 20260822_style_article
Create Date: 2026-08-24 16:56:53.849124
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlalchemy.dialects.postgresql import UUID as GUID

revision = 'b7af20f6f3bb'
down_revision = '20260822_style_article'
branch_labels = None
depends_on = None

# ── WHY THIS REVISION IS WRITTEN DEFENSIVELY ────────────────────────────────
# It was AUTOGENERATED against one live database, so it assumed that database's
# exact state. On a brand-new database it died:
#   * `drawer_pool_bootstrap` has already INSERTed drawer + barcode_registry rows
#     with NULL created_at/updated_at, so a bare `SET NOT NULL` fails with
#     NotNullViolation. Every NOT NULL below backfills first (_not_null).
#   * index / constraint names differ between databases that were built by
#     `create_all` and ones built by this chain, so every drop/create of an
#     index or constraint is IF [NOT] EXISTS.
# Keep this shape: never ship an autogenerated revision unedited — run it on a
# fresh database first (see docs/ALEMBIC_FRESH_DB_NOTES.md).


def _not_null(table, column, fill="now()", type_=None):
    """Backfill NULLs, then SET NOT NULL — safe on populated and empty tables."""
    op.execute(sa.text(f"UPDATE {table} SET {column} = {fill} WHERE {column} IS NULL"))
    op.alter_column(table, column, nullable=False,
                    existing_type=type_ or postgresql.TIMESTAMP(timezone=True))


def _timestamps(table):
    _not_null(table, "created_at")
    _not_null(table, "updated_at")


def _drop_ix(name, table):
    op.drop_index(name, table_name=table, if_exists=True)


def _ix(name, table, cols, unique=False):
    op.create_index(name, table, cols, unique=unique, if_not_exists=True)


def upgrade():
    # ── barcode_registry ────────────────────────────────────────────────────
    _timestamps("barcode_registry")
    for old in ("ix_barcode_code", "ix_barcode_employee", "ix_barcode_order_id",
                "ix_barcode_piece", "ix_barcode_sku_id", "ix_barcode_status",
                "ix_barcode_style_id", "ix_barcode_type"):
        _drop_ix(old, "barcode_registry")
    for col in ("code", "drawer_id", "employee_id", "material_lot_id", "order_id",
                "piece_id", "sku_id", "status", "style_id", "type"):
        _ix(f"ix_barcode_registry_{col}", "barcode_registry", [col])

    # ── bom ─────────────────────────────────────────────────────────────────
    op.add_column("bom", sa.Column("style_signature", sa.String(length=120),
                                   nullable=True), if_not_exists=True)
    _ix("ix_bom_style_signature", "bom", ["style_signature"])
    op.execute("ALTER TABLE bom DROP CONSTRAINT IF EXISTS uq_bom_submission_style")
    op.create_unique_constraint("uq_bom_submission_style", "bom",
                                ["submission_id", "style_signature"])

    # ── client_check_rule ───────────────────────────────────────────────────
    _not_null("client_check_rule", "severity", "'warn'", sa.VARCHAR(length=10))
    op.alter_column("client_check_rule", "params",
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True, postgresql_using="params::jsonb")
    _not_null("client_check_rule", "sort_order", "0", sa.INTEGER())
    _timestamps("client_check_rule")

    # ── client_order: unique constraint -> unique index ─────────────────────
    op.execute("ALTER TABLE client_order "
               "DROP CONSTRAINT IF EXISTS uq_client_order_order_number")
    _ix("ix_client_order_order_number", "client_order", ["order_number"], unique=True)

    # ── cost_catalog_line ───────────────────────────────────────────────────
    _not_null("cost_catalog_line", "sort_order", "0", sa.INTEGER())
    _timestamps("cost_catalog_line")

    # ── drawer ──────────────────────────────────────────────────────────────
    _timestamps("drawer")
    _ix("ix_drawer_current_piece_id", "drawer", ["current_piece_id"])

    # ── dxf_yield / employee / fabric_role ──────────────────────────────────
    _not_null("dxf_yield", "updated_at")
    _drop_ix("uq_employee_name_ci", "employee")
    _timestamps("fabric_role")

    # ── material_lot ────────────────────────────────────────────────────────
    op.alter_column("material_lot", "attributes",
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True, postgresql_using="attributes::jsonb")
    _timestamps("material_lot")
    _drop_ix("uq_material_lot_spec", "material_lot")
    _ix("ix_material_lot_supplier_id", "material_lot", ["supplier_id"])

    # ── material_rate ───────────────────────────────────────────────────────
    op.alter_column("material_rate", "id", existing_type=sa.VARCHAR(length=36),
                    type_=GUID(), existing_nullable=False,
                    postgresql_using="id::uuid")
    _timestamps("material_rate")
    _drop_ix("ix_material_rate_current", "material_rate")
    _ix("ix_material_rate_is_current", "material_rate", ["is_current"])

    # ── material_receipt / material_reservation / material_supplier ─────────
    _timestamps("material_receipt")
    _drop_ix("ix_material_receipt_lot", "material_receipt")
    _ix("ix_material_receipt_material_lot_id", "material_receipt", ["material_lot_id"])
    _ix("ix_material_receipt_supplier_order_id", "material_receipt", ["supplier_order_id"])

    _timestamps("material_reservation")
    _drop_ix("ix_material_reservation_lot", "material_reservation")
    _ix("ix_material_reservation_material_lot_id", "material_reservation", ["material_lot_id"])
    _ix("ix_material_reservation_status", "material_reservation", ["status"])

    _timestamps("material_supplier")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wage_line_detail_wage_run_id'), table_name='wage_line_detail')
    op.drop_index(op.f('ix_wage_line_detail_employee_id'), table_name='wage_line_detail')
    op.create_index(op.f('ix_wage_line_detail_run'), 'wage_line_detail', ['wage_run_id'], unique=False)
    op.drop_constraint(op.f('fk_supplier_order_ordered_by_app_user'), 'supplier_order', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_order_supplier_id'), table_name='supplier_order')
    op.alter_column('supplier_order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_order', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_submission_created_by_app_user'), 'submission', type_='foreignkey')
    op.drop_constraint(op.f('fk_style_consumption_template_confirmed_by_app_user'), 'style_consumption_template', type_='foreignkey')
    op.drop_column('style', 'material_spec_no_accessories')
    op.drop_column('style', 'material_spec_confirmed_by')
    op.drop_column('style', 'material_spec_confirmed_at')
    op.drop_constraint(op.f('fk_purchase_order_approved_by_app_user'), 'purchase_order', type_='foreignkey')
    op.drop_constraint(op.f('fk_purchase_order_rejected_by_app_user'), 'purchase_order', type_='foreignkey')
    op.drop_constraint(op.f('fk_purchase_order_created_by_app_user'), 'purchase_order', type_='foreignkey')
    op.drop_constraint(op.f('fk_production_tracking_updated_by_app_user'), 'production_tracking', type_='foreignkey')
    op.drop_index(op.f('ix_production_event_lining_lot_id'), table_name='production_event')
    op.drop_index(op.f('ix_production_event_leather_lot_id'), table_name='production_event')
    op.drop_constraint(op.f('fk_notification_recipient_user_id_app_user'), 'notification', type_='foreignkey')
    op.alter_column('material_supplier', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_supplier', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_material_reservation_status'), table_name='material_reservation')
    op.drop_index(op.f('ix_material_reservation_material_lot_id'), table_name='material_reservation')
    op.create_index(op.f('ix_material_reservation_lot'), 'material_reservation', ['material_lot_id'], unique=False)
    op.alter_column('material_reservation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_reservation', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_material_receipt_received_by_app_user'), 'material_receipt', type_='foreignkey')
    op.drop_index(op.f('ix_material_receipt_supplier_order_id'), table_name='material_receipt')
    op.drop_index(op.f('ix_material_receipt_material_lot_id'), table_name='material_receipt')
    op.create_index(op.f('ix_material_receipt_lot'), 'material_receipt', ['material_lot_id'], unique=False)
    op.alter_column('material_receipt', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_receipt', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_material_rate_is_current'), table_name='material_rate')
    op.create_index(op.f('ix_material_rate_current'), 'material_rate', ['material_key', 'is_current'], unique=False)
    op.alter_column('material_rate', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_rate', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_rate', 'id',
               existing_type=GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using='id::varchar(36)')
    op.drop_index(op.f('ix_material_lot_supplier_id'), table_name='material_lot')
    op.create_index(op.f('uq_material_lot_spec'), 'material_lot', ['category', 'subtype', 'article', 'colour', 'thickness', 'size'], unique=True, postgresql_where='is_active', postgresql_nulls_not_distinct=True)
    op.alter_column('material_lot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_lot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_lot', 'attributes',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_inventory_check_run_by_app_user'), 'inventory_check', type_='foreignkey')
    op.alter_column('fabric_role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fabric_role', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uq_employee_name_ci'), 'employee', [sa.literal_column('lower(name::text)')], unique=True)
    op.drop_constraint(op.f('fk_dxf_yield_observation_confirmed_by_app_user'), 'dxf_yield_observation', type_='foreignkey')
    op.alter_column('dxf_yield', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dxf_yield', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_drawer_current_piece_id'), table_name='drawer')
    op.alter_column('drawer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drawer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('drawer', 'accessories_in')
    op.drop_constraint(op.f('fk_document_uploaded_by_app_user'), 'document', type_='foreignkey')
    op.alter_column('cost_catalog_line', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_catalog_line', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_catalog_line', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_client_order_order_number'), table_name='client_order')
    op.create_unique_constraint(op.f('uq_client_order_order_number'), 'client_order', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('client_check_rule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_check_rule', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_check_rule', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_check_rule', 'params',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('client_check_rule', 'severity',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'warn'::character varying"))
    op.drop_constraint(op.f('fk_bom_cutting_confirmed_by_app_user'), 'bom', type_='foreignkey')
    op.drop_constraint(op.f('fk_bom_approved_by_app_user'), 'bom', type_='foreignkey')
    op.drop_constraint(op.f('fk_bom_rejected_by_app_user'), 'bom', type_='foreignkey')
    op.drop_constraint('uq_bom_submission_style', 'bom', type_='unique')
    op.drop_index(op.f('ix_bom_style_signature'), table_name='bom')
    op.drop_column('bom', 'style_signature')
    op.drop_index(op.f('ix_barcode_registry_type'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_style_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_status'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_sku_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_piece_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_order_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_material_lot_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_employee_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_drawer_id'), table_name='barcode_registry')
    op.drop_index(op.f('ix_barcode_registry_code'), table_name='barcode_registry')
    op.create_index(op.f('ix_barcode_type'), 'barcode_registry', ['type'], unique=False)
    op.create_index(op.f('ix_barcode_style_id'), 'barcode_registry', ['style_id'], unique=False)
    op.create_index(op.f('ix_barcode_status'), 'barcode_registry', ['status'], unique=False)
    op.create_index(op.f('ix_barcode_sku_id'), 'barcode_registry', ['sku_id'], unique=False)
    op.create_index(op.f('ix_barcode_piece'), 'barcode_registry', ['piece_id'], unique=False)
    op.create_index(op.f('ix_barcode_order_id'), 'barcode_registry', ['order_id'], unique=False)
    op.create_index(op.f('ix_barcode_employee'), 'barcode_registry', ['employee_id'], unique=False)
    op.create_index(op.f('ix_barcode_code'), 'barcode_registry', ['code'], unique=False)
    op.alter_column('barcode_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('barcode_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_audit_log_actor_user_id_app_user'), 'audit_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_attendance_log_recorded_by_user_id_app_user'), 'attendance_log', type_='foreignkey')
    # ### end Alembic commands ###
