"""Order hierarchy: Client -> ClientOrder -> Style -> SKU.

NAMING (BOM Procurement Workflow, Stage 0)
    The buyer order table is named `client_order` — the workflow doc calls it the
    "order", and `order` is a SQL reserved word, so the physical name is
    `client_order`. The name `purchase_order` now belongs to the SUPPLIER PO in the
    procurement module. (Previously this table was `purchase_order` / class
    `PurchaseOrder` with a `po_number` column — see the Stage-0 rename migration.)

The SKU (style + colour + size) is the atomic unit everything else joins to.
"""
import uuid
from datetime import date
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    Date,
    ForeignKey,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.core.models import GUID, TimestampMixin, UUIDMixin


class Client(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "client"
    name: Mapped[str] = mapped_column(String(200), index=True)
    country: Mapped[str | None] = mapped_column(String(100))
    # Clients differ on currency / size system / branding (Beau Geste: USD,
    # letter sizes, Japanese; Jackie: EUR, EU-numeric, brand "THE JACKIE LEATHER").
    code: Mapped[str | None] = mapped_column(String(40), unique=True, index=True)  # KJ, GGZ, ...
    currency: Mapped[str | None] = mapped_column(String(3))             # USD / EUR / INR
    default_size_system: Mapped[str | None] = mapped_column(String(10))  # LETTER / EU / MIXED
    brand: Mapped[str | None] = mapped_column(String(120))
    label: Mapped[str | None] = mapped_column(String(120))
    contact_email: Mapped[str | None] = mapped_column(String(160))
    contact_phone: Mapped[str | None] = mapped_column(String(50))
    address: Mapped[str | None] = mapped_column(String(400))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    client_orders: Mapped[list["ClientOrder"]] = relationship(
        back_populates="client", cascade="all, delete-orphan"
    )


class ClientOrder(Base, UUIDMixin, TimestampMixin):
    """A buyer's order. Renamed from `purchase_order` so that name is free for the
    supplier PO (procurement module). `order_number` holds 1579 / "Proposta N.2"."""
    __tablename__ = "client_order"
    client_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("client.id"), index=True)
    order_number: Mapped[str] = mapped_column(String(50), index=True)
    order_date: Mapped[date | None] = mapped_column(Date)
    delivery_deadline: Mapped[date | None] = mapped_column(Date)
    sea_cutoff_date: Mapped[date | None] = mapped_column(Date)  # last day to make sea freight
    ship_mode: Mapped[str] = mapped_column(String(10), default="sea")  # sea | air
    currency: Mapped[str | None] = mapped_column(String(3))
    agent: Mapped[str | None] = mapped_column(String(120))
    line: Mapped[str | None] = mapped_column(String(120))   # Jackie "LINEA" distribution line
    # The uploaded order sheet this order was extracted from (procurement.document).
    # Referenced by table name only — no Python import, no layering violation.
    # `use_alter=True` breaks the 3-table create-order cycle
    # document → submission → client_order → document (the order is derived from the
    # document in Stage 2, so this is the link added LAST). Without it SQLAlchemy
    # cannot sort {client_order, document, submission} and an autogenerated baseline
    # emits the CREATE TABLEs in the wrong order → "relation does not exist".
    source_document_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey("document.id", use_alter=True,
                   name="fk_client_order_source_document"),
        nullable=True, index=True,
    )
    client: Mapped["Client"] = relationship(back_populates="client_orders")
    styles: Mapped[list["Style"]] = relationship(
        back_populates="client_order", cascade="all, delete-orphan"
    )


class Style(Base, UUIDMixin, TimestampMixin):
    """One model, e.g. CARNABY. A client order has many styles."""
    __tablename__ = "style"
    client_order_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("client_order.id"), index=True
    )
    name: Mapped[str] = mapped_column(String(120), index=True)
    gender: Mapped[str | None] = mapped_column(String(20))
    label: Mapped[str | None] = mapped_column(String(80))
    article: Mapped[str | None] = mapped_column(String(80))
    thickness: Mapped[str | None] = mapped_column(String(40))
    # BOM workflow additions (straight off the order/spec sheets).
    season: Mapped[str | None] = mapped_column(String(20))         # 2026AW / SS26
    customer_ref: Mapped[str | None] = mapped_column(String(80))   # CR1-02F5-PL02
    internal_ref: Mapped[str | None] = mapped_column(String(80))   # A32073-44
    unit_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str | None] = mapped_column(String(3))
    # Combined styles ("CLERMONT + VEST") reference the base style. Column only —
    # no self-relationship needed for Stage 0.
    base_style_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(), ForeignKey("style.id"), nullable=True, index=True
    )
    client_order: Mapped["ClientOrder"] = relationship(back_populates="styles")
    skus: Mapped[list["SKU"]] = relationship(
        back_populates="style", cascade="all, delete-orphan"
    )
    components: Mapped[list["StyleComponent"]] = relationship(
        back_populates="style", cascade="all, delete-orphan"
    )


class StyleComponent(Base, UUIDMixin, TimestampMixin):
    """An add-on / combined-style component. Jackie's split prices ("66+8", "39+7")
    and "+ DETACH" / "+ VEST" add-ons can't live in a single price column."""
    __tablename__ = "style_component"
    style_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("style.id"), index=True)
    component_name: Mapped[str] = mapped_column(String(80))   # VEST, FUR DETACH, KNIT, NYLON
    add_on_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str | None] = mapped_column(String(3))
    style: Mapped["Style"] = relationship(back_populates="components")


class SKU(Base, UUIDMixin, TimestampMixin):
    """A specific style, in a specific colour, in a specific size.

    This is the unit production events are logged against.
    """
    __tablename__ = "sku"
    __table_args__ = (
        UniqueConstraint("style_id", "color_code", "size", name="uq_sku_identity"),
    )
    style_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("style.id"), index=True)
    color_code: Mapped[str] = mapped_column(String(40))     # "57", "J24"
    color_name: Mapped[str | None] = mapped_column(String(80))  # "PINE GREEN"
    size: Mapped[str] = mapped_column(String(10))           # "M", "42" — string by design
    qty_ordered: Mapped[int] = mapped_column(Integer, default=0)
    # johnpeter.xlsx carries SUEDE + KNIT + NYLON colour dimensions per line; the
    # suede/main colour stays in color_code/color_name, the other two live here.
    nylon_color: Mapped[str | None] = mapped_column(String(80))
    knit_color: Mapped[str | None] = mapped_column(String(80))
    style: Mapped["Style"] = relationship(back_populates="skus")
