"""Order hierarchy: Client -> ClientOrder -> Style -> SKU.

NAMING (BOM Procurement Workflow, Stage 0)
    The buyer order table is named `client_order` — the workflow doc calls it the
    "order", and `order` is a SQL reserved word, so the physical name is
    `client_order`. The name `purchase_order` now belongs to the SUPPLIER PO in the
    procurement module. (Previously this table was `purchase_order` / class
    `PurchaseOrder` with a `po_number` column — see the Stage-0 rename migration.)

The SKU (style + colour + size) is the atomic unit everything else joins to.
"""
import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.core.enums import ProductionReleaseStatus
from app.core.models import GUID, TimestampMixin, UUIDMixin


class Client(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "client"
    name: Mapped[str] = mapped_column(String(200), index=True)
    country: Mapped[str | None] = mapped_column(String(100))
    # Clients differ on currency / size system / branding (Beau Geste: USD,
    # letter sizes, Japanese; Jackie: EUR, EU-numeric, brand "THE JACKIE LEATHER").
    code: Mapped[str | None] = mapped_column(String(40), unique=True, index=True)  # KJ, GGZ, ...
    currency: Mapped[str | None] = mapped_column(String(3))             # USD / EUR / INR
    default_size_system: Mapped[str | None] = mapped_column(String(10))  # LETTER / EU / MIXED
    brand: Mapped[str | None] = mapped_column(String(120))
    label: Mapped[str | None] = mapped_column(String(120))
    contact_email: Mapped[str | None] = mapped_column(String(160))
    contact_phone: Mapped[str | None] = mapped_column(String(50))
    address: Mapped[str | None] = mapped_column(String(400))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    client_orders: Mapped[list["ClientOrder"]] = relationship(
        back_populates="client", cascade="all, delete-orphan"
    )


class ClientOrder(Base, UUIDMixin, TimestampMixin):
    """A buyer's order. Renamed from `purchase_order` so that name is free for the
    supplier PO (procurement module). `order_number` holds 1579 / "Proposta N.2"."""
    __tablename__ = "client_order"
    client_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("client.id"), index=True)
    order_number: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    order_date: Mapped[date | None] = mapped_column(Date)
    delivery_deadline: Mapped[date | None] = mapped_column(Date)
    sea_cutoff_date: Mapped[date | None] = mapped_column(Date)  # last day to make sea freight
    ship_mode: Mapped[str] = mapped_column(String(10), default="sea")  # sea | air
    currency: Mapped[str | None] = mapped_column(String(3))
    agent: Mapped[str | None] = mapped_column(String(120))
    line: Mapped[str | None] = mapped_column(String(120))   # Jackie "LINEA" distribution line
    # The uploaded order sheet this order was extracted from (procurement.document).
    # Referenced by table name only — no Python import, no layering violation.
    # `use_alter=True` breaks the 3-table create-order cycle
    # document → submission → client_order → document (the order is derived from the
    # document in Stage 2, so this is the link added LAST). Without it SQLAlchemy
    # cannot sort {client_order, document, submission} and an autogenerated baseline
    # emits the CREATE TABLEs in the wrong order → "relation does not exist".
    #
    # `use_alter` only fixes CREATE order. It says nothing about DELETE, and the
    # same cycle deadlocks there: a document cannot be deleted while an order
    # names it as its source, and the order cannot be deleted first because the
    # submission in the middle points at both. ondelete="SET NULL" is the right
    # rule here because the pointer is PROVENANCE, not ownership — the order's
    # own data was extracted at upload time and is fully intact without the
    # source file, so losing the file must not take the order with it.
    source_document_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(),
        ForeignKey("document.id", ondelete="SET NULL", use_alter=True,
                   name="fk_client_order_source_document"),
        nullable=True, index=True,
    )
    client: Mapped["Client"] = relationship(back_populates="client_orders")
    styles: Mapped[list["Style"]] = relationship(
        back_populates="client_order", cascade="all, delete-orphan"
    )


class Style(Base, UUIDMixin, TimestampMixin):
    """One model, e.g. CARNABY. A client order has many styles."""
    __tablename__ = "style"
    client_order_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("client_order.id"), index=True
    )
    name: Mapped[str] = mapped_column(String(120), index=True)
    gender: Mapped[str | None] = mapped_column(String(20))
    label: Mapped[str | None] = mapped_column(String(80))
    article: Mapped[str | None] = mapped_column(String(80))
    thickness: Mapped[str | None] = mapped_column(String(40))
    code: Mapped[str | None] = mapped_column(String(200), unique=True, index=True)
    # BOM workflow additions (straight off the order/spec sheets).
    season: Mapped[str | None] = mapped_column(String(20))         # 2026AW / SS26
    customer_ref: Mapped[str | None] = mapped_column(String(80))   # CR1-02F5-PL02
    internal_ref: Mapped[str | None] = mapped_column(String(80))   # A32073-44
    unit_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str | None] = mapped_column(String(3))
    # Combined styles ("CLERMONT + VEST") reference the base style. Column only —
    # no self-relationship needed for Stage 0.
    # SELF-REFERENTIAL, so it is a one-table cycle and deletes deadlock the same
    # way: the base style cannot be removed while a combined style names it.
    # SET NULL, not CASCADE — deleting "CLERMONT" must not silently delete
    # "CLERMONT + VEST" and every piece hanging off it. The combined style simply
    # stops claiming a base.
    base_style_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID(), ForeignKey("style.id", ondelete="SET NULL"),
        nullable=True, index=True
    )
    # ── THE PRODUCTION RELEASE GATE (change-list item 9) ────────────────────
    # A breakdown upload writes styles/SKUs and STOPS. Nothing is minted until
    # the DM releases the style, which is what creates its per-piece barcodes and
    # consumes drawers from a finite pool.
    #
    # VARCHAR, NOT A NATIVE PG ENUM — deliberately, and the reason is scar tissue:
    # `app_user.role` is a native enum and adding a label to it has broken a
    # deploy three separate times (CLAUDE.md §13). Every module-level status in
    # this schema is a str-Enum over VARCHAR for exactly that reason. Adding
    # a fourth release state must never need an ALTER TYPE.
    production_status: Mapped[str] = mapped_column(
        String(20), default=ProductionReleaseStatus.DRAFT.value,
        server_default=ProductionReleaseStatus.DRAFT.value, index=True,
    )
    released_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    released_by: Mapped[str | None] = mapped_column(String(120))
    # ── WHEN THIS STYLE SHIPS ────────────────────────────────────────────────
    # Read from the DELIVERY column of the breakdown sheet, which prints it once
    # per style row.
    #
    # PER STYLE, NOT PER ORDER, and that is the whole reason this column exists
    # rather than reusing ClientOrder.delivery_deadline. One order sheet routinely
    # carries a main-season style and an outlet style with different ship dates;
    # collapsing them onto the order would make the earlier one invisible and the
    # later one a lie. `delivery_deadline` stays exactly as it is — the order's
    # own commercial deadline — and the two answer different questions.
    #
    # NULLABLE because plenty of sheets simply do not print a delivery column
    # (the John Peter consolidated sheets do not). That is not an error and must
    # not be treated as one.
    delivery_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    # ── THE LINING DECLARATION (asked at release) ───────────────────────────
    # "Does this style take a lining?", answered by the DM at the moment they
    # release the style into production, and authoritative from then on — see
    # core/lining_rules.py for why an explicit answer outranks the name/colour
    # inference in BOTH directions.
    #
    # NULLABLE, AND THE NULL IS LOAD-BEARING: it means NOBODY HAS BEEN ASKED,
    # which is true of every style released before this column existed. Those
    # fall back to inference and keep exactly the verdict they have today, so
    # adding this column changes nothing retroactively for garments already on
    # the floor. A three-state answer needs three states; a NOT NULL default of
    # False would silently declare 1,400 live pieces leather-only.
    needs_lining: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # ── THE MATERIAL SPEC HEADER (the per-piece recipe, asked before release) ─
    # The LINES live in style_material_spec; these three columns are the header:
    # who signed the recipe off, when, and the one answer the lines themselves
    # cannot express.
    #
    # WHY THREE COLUMNS AND NOT A HEADER TABLE. A header table earns its keep
    # only if the spec is VERSIONED, and nobody has asked for that. Style already
    # carries exactly this shape of question — needs_lining above, beside
    # released_at / released_by — so the recipe declaration is modelled the same
    # way as the lining declaration it sits next to.
    #
    # PREFIXED `material_spec_` DELIBERATELY: a bare `spec_` reads as SpecSheet,
    # which is the BOM module's (different, Phase-2) thing.
    material_spec_confirmed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True))
    material_spec_confirmed_by: Mapped[str | None] = mapped_column(String(120))
    # THREE-STATE, and the NULL is load-bearing exactly as it is for
    # needs_lining: NULL means nobody has been asked. A recipe with no accessory
    # lines is ambiguous on its own — it could be a jacket that genuinely takes
    # none, or one whose buttons nobody entered yet — and releasing the second
    # kind silently is how the whole order reaches the store with no kit. True is
    # the DM saying "this style takes no accessories"; that is the only thing
    # that lets an accessory-free style through the release gate.
    material_spec_no_accessories: Mapped[bool | None] = mapped_column(
        Boolean, nullable=True)

    client_order: Mapped["ClientOrder"] = relationship(back_populates="styles")
    skus: Mapped[list["SKU"]] = relationship(
        back_populates="style", cascade="all, delete-orphan"
    )
    components: Mapped[list["StyleComponent"]] = relationship(
        back_populates="style", cascade="all, delete-orphan"
    )


# ══════════════════════════════════════════════════════════════════════════════
# THE ONE DEFINITION OF "THIS STYLE IS IN PRODUCTION"
# ══════════════════════════════════════════════════════════════════════════════
# Uploading a breakdown sheet is NOT production. The sheet lands as DRAFT rows
# that mint nothing, consume no drawers, and must be invisible to every service
# that reports on the factory floor — dashboard counts, payroll landing screens,
# analytics. Only a style the DM has explicitly RELEASED has pieces, barcodes and
# workers against it, and only then does it become something the business can be
# asked questions about.
#
# WHY THIS IS ONE SHARED EXPRESSION AND NOT A `.where()` REPEATED PER QUERY.
# The bug that produced it: the dashboard totalled `SUM(SKU.qty_ordered)` over
# every style regardless of status, while `minted_pieces` counted Piece rows that
# only exist after release. Uploading a 1,425-piece sheet therefore added 1,425
# to the order total immediately, and releasing it added 1,425 more pieces — the
# same garments counted twice, in two figures that no longer described the same
# population. Any query that counts work must apply the SAME predicate, so the
# predicate gets exactly one home.
#
# RELEASED ONLY — deliberately not "anything except DRAFT". A CANCELLED style is
# work that was pulled; its history (production events, wage lines) stays intact
# and still pays, but it must drop out of the live counts, or a cancelled order
# inflates the floor's targets forever.
def style_in_production():
    """SQL predicate: this Style is released into production.

    Use in any query that counts, totals, or lists factory work:

        stmt = stmt.join(Style, ...).where(style_in_production())
    """
    return Style.production_status == ProductionReleaseStatus.RELEASED.value


# The same answer for a Style object already in memory.
def is_in_production(style) -> bool:
    return (getattr(style, "production_status", None)
            == ProductionReleaseStatus.RELEASED.value)


# ══════════════════════════════════════════════════════════════════════════════
# MAY THE MATERIAL SPEC STILL BE EDITED?
# ══════════════════════════════════════════════════════════════════════════════
# The recipe is frozen by the same event that freezes the breakdown behind it:
# release. Once a style is RELEASED its pieces carry printed barcodes and its
# spec is being SPENT — every kit scan decrements stock against these lines — so
# editing a line underneath live garments would make the ledger disagree with
# what was physically issued.
#
# CANCELLED is editable on purpose. It never minted anything, and a style pulled
# and later re-uploaded should not have to fight a frozen recipe.
#
# THIS IS NOT A DEAD END FOR A WRONG SPEC. A typo'd button article on a released
# style is corrected on the floor through POST /materials/issues, which records
# what was ACTUALLY issued (source=MANUAL) without unfreezing the recipe. That
# escape hatch is what makes freezing acceptable.
def spec_editable(style) -> bool:
    """True when this style's material spec may still be written to."""
    status = (getattr(style, "production_status", None)
              or ProductionReleaseStatus.DRAFT.value)
    return status != ProductionReleaseStatus.RELEASED.value


class StyleComponent(Base, UUIDMixin, TimestampMixin):
    """An add-on / combined-style component. Jackie's split prices ("66+8", "39+7")
    and "+ DETACH" / "+ VEST" add-ons can't live in a single price column."""
    __tablename__ = "style_component"
    style_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("style.id"), index=True)
    component_name: Mapped[str] = mapped_column(String(80))   # VEST, FUR DETACH, KNIT, NYLON
    add_on_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str | None] = mapped_column(String(3))
    style: Mapped["Style"] = relationship(back_populates="components")


class SKU(Base, UUIDMixin, TimestampMixin):
    """A specific style, in a specific colour, in a specific size.

    This is the unit production events are logged against.
    """
    __tablename__ = "sku"
    __table_args__ = (
        UniqueConstraint("style_id", "color_code", "size", name="uq_sku_identity"),
    )
    style_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("style.id"), index=True)
    color_code: Mapped[str] = mapped_column(String(40))     # "57", "J24"
    color_name: Mapped[str | None] = mapped_column(String(80))  # "PINE GREEN"
    size: Mapped[str] = mapped_column(String(10))           # "M", "42" — string by design
    qty_ordered: Mapped[int] = mapped_column(Integer, default=0)
    code: Mapped[str | None] = mapped_column(String(120), unique=True, index=True)
    # johnpeter.xlsx carries SUEDE + KNIT + NYLON colour dimensions per line; the
    # suede/main colour stays in color_code/color_name, the other two live here.
    nylon_color: Mapped[str | None] = mapped_column(String(80))
    knit_color: Mapped[str | None] = mapped_column(String(80))
    style: Mapped["Style"] = relationship(back_populates="skus")
    order_lines: Mapped[list["SkuOrderLine"]] = relationship(back_populates="sku", cascade="all, delete-orphan")

class SkuOrderLine(Base, UUIDMixin, TimestampMixin):
    """One dated order-line quantity for a SKU.
 
    The breakdown sheet lists the same (style, colour, size) across several dated
    rows. The SKU stays unique (one per triple, qty_ordered = SUM of its lines);
    each dated row is kept here for traceability. Multiple lines may share a
    (sku_id, order_date) — source_row distinguishes them."""
    __tablename__ = "sku_order_line"
    sku_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("sku.id", ondelete="CASCADE"), index=True
    )
    order_date: Mapped[date | None] = mapped_column(Date, index=True)
    qty: Mapped[int] = mapped_column(Integer, default=0)
    source_row: Mapped[int | None] = mapped_column(Integer)
    sku: Mapped["SKU"] = relationship(back_populates="order_lines")