"""
SYSTEM · a readable REQUEST/RESPONSE TRANSCRIPT of the main flows.

WHAT THIS IS FOR
    A Postman-console view of the API without Postman, and without pointing
    anything at the production database. It drives the real FastAPI app over
    ASGI against the in-memory SQLite harness, and writes every call — method,
    URL, request body, status, response body — to `docs/api_transcript.md`.

    Run it whenever you want to see what an endpoint actually returns:

        pytest tests/system/test_api_transcript.py -q
        -> docs/api_transcript.md

    It is a TEST, not a script, so the transcript can never drift from working
    behaviour: the assertions below fail if the flow stops behaving, and a
    transcript is only produced by a run that passed.

WHY NOT JUST POINT POSTMAN AT THE RUNNING APP
    You can, and should — `postman_collection.json` is generated for exactly
    that. But the .env in this repo currently names the PRODUCTION Supabase
    database, so "run the server and try the endpoints" would write payroll runs
    and release styles in production. This file exercises the same routes against
    a throwaway database instead.
"""
import json
import pathlib
from datetime import date, timedelta

import pytest

from app.core.enums import UserRole, WageType
from app.modules.clients import models as cm
from app.modules.employees import models as em
from app.modules.production import models as pm
from app.modules.wages.models import Rate

TRANSCRIPT = pathlib.Path(__file__).resolve().parents[2] / "docs" / "api_transcript.md"

END = date.today() - timedelta(days=1)
START = END - timedelta(days=13)
DAY = START + timedelta(days=2)


class Recorder:
    """Wraps the httpx client and appends each exchange to the transcript."""

    def __init__(self, client):
        self.client = client
        self.lines: list[str] = []
        self.n = 0

    async def call(self, method: str, url: str, *, note: str = "", **kw):
        self.n += 1
        r = await self.client.request(method, url, **kw)
        body = kw.get("json")
        self.lines.append(f"\n### {self.n}. {method.upper()} `{url}`\n")
        if note:
            self.lines.append(f"> {note}\n")
        if body is not None:
            self.lines.append("**Request**\n\n```json\n"
                              + json.dumps(body, indent=2) + "\n```\n")
        try:
            payload = r.json()
            shown = json.dumps(payload, indent=2, default=str)
        except Exception:
            shown = r.text
        if len(shown) > 2500:
            shown = shown[:2500] + "\n… (truncated)"
        self.lines.append(f"**Response — `{r.status_code}`**\n\n```json\n{shown}\n```\n")
        return r

    def write(self, title: str):
        TRANSCRIPT.parent.mkdir(parents=True, exist_ok=True)
        header = (
            f"# {title}\n\n"
            "Generated by `pytest tests/system/test_api_transcript.py`.\n"
            "Every exchange below is a real call through the FastAPI app "
            "(ASGI, throwaway SQLite database — never production).\n"
        )
        TRANSCRIPT.write_text(header + "".join(self.lines), encoding="utf-8")


async def _world(db):
    """Two orders sharing a client, an employee, and one day of cut work."""
    client = cm.Client(name="John Peter")
    db.add(client)
    await db.flush()
    op = pm.Operation(code="LEATHER_CUTTING", label="Leather Cutting", sequence=1)
    db.add(op)
    await db.flush()
    cutter = em.Employee(name="RAGAVAN L", designation="CUTTER",
                         wage_type=WageType.PIECE_RATE, is_active=True)
    db.add(cutter)
    await db.flush()

    made = {}
    for tag, article in (("KJ2451", "GOAT SUEDE"), ("KJ2452", "LAMB NAPPA")):
        order = cm.ClientOrder(client_id=client.id, order_number=tag)
        db.add(order)
        await db.flush()
        style = cm.Style(client_order_id=order.id, name="CLERMONT", article=article,
                         code=f"{tag}-CLERMONT-{article.replace(' ', '_')}",
                         production_status="RELEASED")
        db.add(style)
        await db.flush()
        sku = cm.SKU(style_id=style.id, color_code="57", color_name="DARK BROWN",
                     size="46", qty_ordered=4,
                     code=f"{style.code}-DARK_BROWN-46")
        db.add(sku)
        await db.flush()
        db.add(pm.ProductionEvent(sku_id=sku.id, operation_id=op.id,
                                  employee_id=cutter.id, work_date=DAY, qty=4,
                                  entered_by="transcript"))
        db.add(Rate(style_id=style.id, operation_id=op.id, rate=12.5,
                    effective_from=START))
        made[tag] = dict(order=order, style=style, sku=sku)
    await db.commit()
    return made


@pytest.mark.asyncio
async def test_transcript_of_the_wage_and_dashboard_flows(db, api_client, as_role):
    """Drives the flows that were just changed, and records them."""
    await _world(db)
    as_role(UserRole.DIRECT_MANAGER)
    rec = Recorder(api_client)

    # ── what the floor sees ──────────────────────────────────────────────────
    d = await rec.call("GET", "/api/v1/dashboard/direct-manager",
                       note="`total_order_pieces` and `minted_pieces` count only "
                            "RELEASED styles, so an uploaded-but-unreleased "
                            "breakdown contributes nothing and cannot be counted "
                            "twice once it is released.")
    assert d.status_code == 200, d.text

    # ── payroll: the scoping rules ───────────────────────────────────────────
    body_a = {"period_start": START.isoformat(), "period_end": END.isoformat(),
              "order_number": "KJ2451"}
    a = await rec.call("POST", "/api/v1/wages/runs", json=body_a,
                       note="Scoped to ONE order. `piece_rate_only` is true — a "
                            "monthly salary belongs to a person, not a style.")
    assert a.status_code == 201, a.text

    body_b = {"period_start": START.isoformat(), "period_end": END.isoformat(),
              "order_number": "KJ2452"}
    b = await rec.call("POST", "/api/v1/wages/runs", json=body_b,
                       note="SAME DATES, different order. Allowed: the two runs "
                            "pay disjoint garments.")
    assert b.status_code == 201, b.text

    body_c = {"period_start": START.isoformat(), "period_end": END.isoformat(),
              "style_code": "KJ2451-CLERMONT-GOAT_SUEDE"}
    c = await rec.call("POST", "/api/v1/wages/runs", json=body_c,
                       note="Same dates, but this style BELONGS to KJ2451 which "
                            "was already paid above — refused as a double payment.")
    assert c.status_code == 409, c.text

    run_id = a.json()["id"]
    await rec.call("GET", f"/api/v1/wages/runs/{run_id}/breakdown",
                   note="Where the money went: by style, by stage, by employee.")

    # ── the payroll landing screen ───────────────────────────────────────────
    await rec.call("GET", "/api/v1/wages/orders",
                   note="Only RELEASED styles are offered a rate card — pricing a "
                        "DRAFT style would price work that does not exist yet.")

    rec.write("KairoX API — request/response transcript")
    assert TRANSCRIPT.exists()
