"""
================================================================================
modules/procurement/enums.py — Value-sets for the BOM Procurement Workflow
================================================================================

These live in the procurement module (not core/enums.py) on purpose: they are
domain-specific to the supplier/BOM/inventory flow, and keeping them here lets
the module be lifted into its own service later without dragging procurement
vocabulary into the shared core.

WHY str-Enums + STRING columns
    Each enum subclasses `str` so `.value` serialises to JSON and stores cleanly.
    The DB columns that hold these are plain VARCHAR storing the enum *value*
    (mirroring the existing `client_order.ship_mode` pattern), NOT native Postgres
    ENUM types. Native enums mean a new PG type per status + an irreversible
    `ALTER TYPE ... ADD VALUE` every time a state is added; plain strings stay
    portable to the SQLite test DB and keep migrations reversible. Validation
    happens at the Pydantic/service layer.
================================================================================
"""
import enum


class DocumentKind(str, enum.Enum):
    ORDER_SHEET = "order_sheet"
    SPEC_SHEET = "spec_sheet"
    BOM_QUOTE = "bom_quote"
    SUPPLIER_PO_PDF = "supplier_po_pdf"


class SpecType(str, enum.Enum):
    """The two real spec-sheet shapes share almost no columns."""
    MEASUREMENT_GRID = "measurement_grid"        # Japanese per-size grid + tolerances
    NARRATIVE_TECHPACK = "narrative_techpack"    # Jackie free-text key->value tech pack


class ExtractionSource(str, enum.Enum):
    """Who produced an extracted value — the audit trail for the LLM policy."""
    DETERMINISTIC = "deterministic"   # rules/regex/normalised string match, no LLM
    GEMINI = "gemini"                 # primary extraction provider
    GROQ = "groq"                     # fallback provider
    MANUAL = "manual"                 # human keyed it (extraction declined to guess)


class BomStatus(str, enum.Enum):
    """Stage-3 approval state machine (stage-3 spec §1):

        draft → ready_for_review → approved | rejected → exported

    `draft`             generated by Stage 2 / re-opened by a late DCM edit or a reopen.
    `ready_for_review`  cutting manager confirmed; awaiting the MD decision (the
                        BOM_AWAITING_REVIEW notification fires on entry).
    `approved`          MD approved — IMMUTABLE; `locked_at` stamped (the legacy `LOCKED`
                        value is the same immutability semantics; approval always locks).
    `rejected`          MD rejected with a reason; terminal until `reopen`.
    `exported`          a PDF has been rendered + stored from the approved/locked BOM.
    """
    DRAFT = "draft"
    READY_FOR_REVIEW = "ready_for_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    LOCKED = "locked"
    EXPORTED = "exported"


class DcmSource(str, enum.Enum):
    """Where a material line's DCM (dm² consumed per garment) came from — the spine
    of Stage 2 (§2). An ordered fallback: a lower-numbered source always wins when
    available, and every material `bom_item` is STAMPED with its source + a
    confidence so an `ai_estimate` can never silently become a final value.

        TEMPLATE       a previously CONFIRMED consumption for this style/material
                       (the DCM memory; conf ~0.95) — cheapest + most trustworthy.
        SIMILAR_STYLE  nearest confirmed template above a similarity floor (~0.7).
        AI_ESTIMATE    last resort: POM area × wastage heuristic (conf ≤0.5, FLAGGED)
                       — the only place finished measurements touch consumption.
        MANUAL         the cutting manager keyed/overrode it (conf 1.00) — the source
                       of truth; written back into the template memory on confirm.
    """
    TEMPLATE = "template"
    SIMILAR_STYLE = "similar_style"
    AI_ESTIMATE = "ai_estimate"
    MANUAL = "manual"


class BomItemCategory(str, enum.Enum):
    MAIN_MATERIAL = "main_material"
    SUB_MATERIAL = "sub_material"
    LINING = "lining"
    INTERLINING = "interlining"
    THREAD = "thread"
    ACCESSORY = "accessory"
    MANUFACTURING = "manufacturing"
    PACKAGING = "packaging"
    FOB_CHARGE = "fob_charge"


class InventoryCheckStatus(str, enum.Enum):
    RUNNING = "running"
    COMPLETE = "complete"


class InventoryLineStatus(str, enum.Enum):
    SUFFICIENT = "sufficient"
    PARTIAL = "partial"
    OUT_OF_STOCK = "out_of_stock"


class ReservationStatus(str, enum.Enum):
    """Lifecycle of a soft stock allocation (stage-4 spec §3). `active` counts against
    `available` (= qty_on_hand − Σ active); `released` frees it (BOM cancel / reopen /
    re-run); `consumed` = the material was physically issued (Stage 6) — terminal."""
    ACTIVE = "active"
    RELEASED = "released"
    CONSUMED = "consumed"


class MatchMethod(str, enum.Enum):
    """How a BOM line was matched to an inventory_item (stage-4 spec §5) — the audit
    trail for the matcher. `key` = deterministic normalized-key exact hit; `alias` =
    a curated synonym row; `manual` = a human confirmed it. A fuzzy candidate is only
    ever a non-applied `suggestion` flag, never an auto-bound method."""
    KEY = "key"
    ALIAS = "alias"
    MANUAL = "manual"


class POStatus(str, enum.Enum):
    """Lifecycle of a SUPPLIER purchase order (Stage 5, §3b).

        draft → pending_approval → approved → sent → responded → confirmed
                       │                                 │
                       └→ rejected → draft               └→ escalated → confirmed

    The Stage-5 cross-check inserts `pending_approval`/`approved`/`rejected` between
    `draft` and `sent` (a VARCHAR str-enum add — reversible, no native ALTER TYPE).
    `cancelled` is reachable from any pre-send state."""
    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    SENT = "sent"
    RESPONDED = "responded"
    CONFIRMED = "confirmed"
    ESCALATED = "escalated"
    CANCELLED = "cancelled"


class POResponseChannel(str, enum.Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"      # Stage 5 §7: the first escalation rung
    CALL = "call"


class POResponseStatus(str, enum.Enum):
    PENDING = "pending"
    OPENED = "opened"
    CONFIRMED = "confirmed"
    NO_RESPONSE = "no_response"
    FAILED = "failed"          # a hard bounce / send failure (§5b)


class POTrackingEventType(str, enum.Enum):
    """The unified engagement log on `po_tracking_event` (§6c)."""
    OPEN = "open"              # pixel hit (probabilistic — §6b caveat)
    CLICK = "click"            # wrapped-link redirect (the reliable read signal)
    DELIVERY = "delivery"      # SES delivery event
    BOUNCE = "bounce"          # SES hard/soft bounce
    COMPLAINT = "complaint"    # SES complaint
    WHATSAPP = "whatsapp"      # an escalation WhatsApp send/reply
    CALL = "call"              # an escalation auto-call outcome


class SupplierEmailStatus(str, enum.Enum):
    """`supplier.email_status` — set by §5b bounce feedback."""
    UNKNOWN = "unknown"
    VALID = "valid"
    INVALID = "invalid"


class SupplierType(str, enum.Enum):
    """Curated supplier type (`supplier.supplier_type`), defaulting from the dominant
    history `mode`. Drives the §2 PO template + the §3 cross-check approver routing."""
    LEATHER = "leather"
    ACCESSORY = "accessory"    # accessory / material / trims
    SERVICE = "service"        # service / job-work


class ProductionTrackingStatus(str, enum.Enum):
    """The §8c order/style production ladder (one row per style/order)."""
    AWAITING_BOM = "awaiting_bom"
    BOM_APPROVED = "bom_approved"
    INVENTORY_CHECKED = "inventory_checked"
    PO_RAISED = "po_raised"
    PO_CONFIRMED = "po_confirmed"
    MATERIAL_READY = "material_ready"
    RELEASED_TO_PRODUCTION = "released_to_production"
    IN_PRODUCTION = "in_production"
    COMPLETED = "completed"


class NotificationChannel(str, enum.Enum):
    IN_APP = "in_app"
    EMAIL = "email"
    WHATSAPP = "whatsapp"      # Stage 5 §7
    CALL = "call"


class NotificationType(str, enum.Enum):
    BOM_AWAITING_REVIEW = "bom_awaiting_review"   # Stage 3: MD review notice
    PO_AWAITING_APPROVAL = "po_awaiting_approval"  # Stage 5 §3: cross-check notice
    PO_DISPATCH = "po_dispatch"                    # Stage 5: PO email to supplier
    PO_ESCALATION_WHATSAPP = "po_escalation_whatsapp"  # Stage 5 §7: WhatsApp rung
    ESCALATION_CALL = "escalation_call"            # Stage 5: auto-call rung
    PO_ESCALATION_EXHAUSTED = "po_escalation_exhausted"  # Stage 5 §7: hand to buyer
    MATERIAL_READY = "material_ready"              # Stage 6: MD alert


class NotificationStatus(str, enum.Enum):
    PENDING = "pending"
    SENT = "sent"
    OPENED = "opened"
    RESPONDED = "responded"
    FAILED = "failed"


class SizeSystem(str, enum.Enum):
    """Stored on `client.default_size_system`; orders mix systems per row regardless."""
    LETTER = "letter"   # S, M, L, XL, XXL (Beau Geste)
    EU = "eu"           # 38-62 numeric (Jackie)
    MIXED = "mixed"     # KJ: 25-31 and 46-62 in one order


# ══════════════════════════════════════════════════════════════════════════
# Stage 1 — upload & validation (this spec)
# ══════════════════════════════════════════════════════════════════════════
class SubmissionStatus(str, enum.Enum):
    """Lifecycle of an upload-batch (the pairing key). OPEN until both slots are
    accepted+clean → COMPLETE → CONSUMED once Stage 2 picks it up. REJECTED is a
    terminal manual close."""
    OPEN = "open"
    COMPLETE = "complete"
    CONSUMED = "consumed"        # Stage 2 has locked it; further uploads → 409
    REJECTED = "rejected"


class ValidationStatus(str, enum.Enum):
    """Per-document identity-validation outcome (Document.validation_status)."""
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"    # replaced by a newer upload in the same slot
    NEEDS_MANUAL_REVIEW = "needs_manual_review"   # order/spec-shaped but below accept


class ScanStatus(str, enum.Enum):
    """Virus-scan outcome (Document.scan_status). `skipped` = scanning disabled in
    dev; the completeness gate treats clean and skipped as acceptable."""
    CLEAN = "clean"
    SKIPPED = "skipped"
    INFECTED = "infected"
    ERROR = "error"


class ClassificationMethod(str, enum.Enum):
    """Which gate produced the classification — the audit trail for the LLM policy.
    `heuristic` = free CPU path; `llm` = escalated to Gemini/Groq; `manual` = human."""
    HEURISTIC = "heuristic"
    LLM = "llm"
    MANUAL = "manual"


class ExpectedLayout(str, enum.Enum):
    """A registry hint about a client doc's physical form. `scanned_pdf` tells the
    validator to skip the futile text-layer pass and escalate straight to the LLM."""
    SCANNED_PDF = "scanned_pdf"
    DIGITAL_PDF = "digital_pdf"
    SPREADSHEET = "spreadsheet"


class RejectReason(str, enum.Enum):
    """The stable reason_code catalog returned on rejection (§5b). Each maps to a
    fixed HTTP status in the router."""
    UNSUPPORTED_MIME = "unsupported_mime"          # 415
    FILE_TOO_LARGE = "file_too_large"              # 413
    EMPTY_OR_CORRUPT = "empty_or_corrupt"          # 422
    VIRUS_DETECTED = "virus_detected"              # 422
    SCANNER_UNAVAILABLE = "scanner_unavailable"    # 503
    NOT_AN_ORDER_SHEET = "not_an_order_sheet"      # 422
    NOT_A_SPEC_SHEET = "not_a_spec_sheet"          # 422
    WRONG_SLOT = "wrong_slot"                      # 422
    NEEDS_MANUAL_REVIEW = "needs_manual_review"    # 422
    SUBMISSION_LOCKED = "submission_locked"        # 409
